from langchain_core.messages import SystemMessage
from ..html.xpath_extractor import extract_by_xpath_map_from_html
from ..agent.state import AgentState
from ..utils import get_system_prompt, get_formatted_extracts, get_llm
from ..utils import load_config

ALLOWED_TAGS = [
                # Theme tags
                "2000 Pound Bomb",  
                "Abduction",
                "Abuse",
                "Academia",
                "Accountability",
                "Administrative Detention",
                "Advertisement",
                "Agriculture",
                "AI (Artificial Intelligence)",
                "Aid Distribution",
                "Aid Workers",
                "Airdrops",
                "Air Strike",
                "Amalek",
                "American Society",
                "Amputation",
                "Analysis",
                "Animals",
                "Annexation",
                "Antisemitism",
                "Apartheid",    
                "Appeal to World Leaders",
                "Archaeological Findings",
                "Arms Shipments",
                "Arrest",
                "Assassination",
                "Attacks on Aid Centers",
                "Attacks on Police",
                "Blockade",
                "Blocking Aid",
                "Bombing",
                "Books",
                "Buildings",
                "Burial",
                "Burn Injuries",
                "Burning",
                "Cages",
                "Campaign against UNRWA",
                "Campus Protests",
                "Captivity Conditions", 
                "Ceasefire",
                "Cemetery",
                "Censorship",
                "Children",
                "Civilians",
                "Collective Punishment",
                "Combat Footage",
                "Communication Blackout",
                "Conscientious Objection",
                "Confiscated Assets",
                "Conspiracy Theories",
                "Cooking Gas",
                "Corpses",
                "Corruption",
                "Crimes Against Humanity",
                "Cultural Genocide",
                "Death",
                "Debunked",
                "Dehumanization",
                "Demolition",
                "Destruction",
                "Destruction of Cultural Sites",
                "Detainees",
                "Detention Center",
                "Diplomacy",
                "Disability",
                "Disease",      
                "Disengagement (2005)",
                "Disturbing Content",
                "Domicide",
                "Double Tap Strike", 
                "Doubting the Gaza Death Toll",
                "Drone / Quadcopter",
                "Economy",
                "Education",
                "Elderly",  
                "Electricity",
                "Emigration",
                "Ethnic Cleansing",
                "Execution",    
                "Explosives",
                "Explosive Injuries",
                "Family",
                "Famine",
                "Food",
                "Fuel",
                "Funding",
                "Forced Displacement",
                "Gaza Death Toll",
                "Gaza US Pier",
                "Genocide",
                "Geolocation",      
                "Global Comparisons",
                "Ground Operation",
                "Gunshot Wounds",
                "Hannibal Directive",
                "Healthcare Workers",
                "Hospital",
                "Hospital Conditions",
                "Hostage Deal",
                "Hostage Rescue Operation",
                "Hostages",
                "Human Shields",
                "Humanitarian Aid",
                "Humanitarian Crisis",
                "Humanitarian Law",
                "Humiliation",
                "Hygiene Issues",
                "Incitement to Genocide",
                "Incitement to Violence",
                "Indiscriminate Shooting",
                "Infants",
                "Infrastructure",
                "Injury",
                "International Responsibility",
                "International Sanctions",
                "Interview",
                "Iron Dome",
                "Islamophobia",
                "Israeli Education System",
                "Israeli Far Right",
                "Israeli Media",
                "Israeli Negotiation Team",
                "Israeli Political Right",
                "Israeli Society",
                "Israeli Soldier Movies",
                "Israeli Soldier Photos",
                "Israeli Soldier Testimonies",
                "Jewish Settlements in Gaza",
                "Journalistic Report",
                "Journalists",
                "Leahy Law",
                "Limiting Free Speech",
                "Looting",
                "Malnutrition",
                "Massacres",
                "Mass Casualty",
                "Mass Graves",
                "Mass Killing",
                "Media",
                "Media Bias",
                "Medical Equipment",
                "Medical Supplies",
                "Medicine",
                "Military Bases",
                "Military Correspondent",
                "Misleading/Partially False",
                "Mockery",
                "Mortar",
                "Mosques",
                "Murder",
                "Nakba",
                "News",
                "Occupied Territories",
                "October 7th 2023",
                "Official Report",
                "Official Statement",
                "Open Letter",
                "Opinion",
                "Orphans",
                "Palestinian Citizens of Israel",
                "Palestinian Militants",
                "Palestinian Testimony",
                "Poll",
                "Poverty",
                "Pregnancy",
                "Prisoners",
                "Propaganda",
                "Protest (International)",
                "Protest (Israel)",
                "Protest (Palestinians)",
                "Psychological Trauma",
                "Psychological Warfare",
                "Public Debate",
                "Public Health",
                "Public Opinion",
                "Quantitative Data",
                "Quran",
                "Racism",
                "Reconstruction",
                "Rafah Red Line",
                "Refugees",
                "Religious Right",
                "Rubble",
                "Rules of Engagement",
                "Running Over",
                "Safe Zones",
                "Sanitation",
                "Satellite images",
                "Scholasticide",
                "Schools",
                "Settlements",
                "Settlers Violence",
                "Severe Illnesses",
                "Sexual Violence",
                "Shooting",
                "Snipers",
                "Social Media",
                "Starvation",
                "Summer Conditions",
                "Surveillance",
                "Talkbacks",
                "Tanks",
                "Terrorism",
                "Testimony",
                "The Flour Massacre",
                "The Generals' Plan",
                "Torching Houses",
                "Torture",
                "Toys",
                "Two State Solution",
                "Universities",
                "Urbicide",
                "US-Israeli Relations",
                "US Military Aid",
                "Vandalism",
                "Video Games",
                "Violence",
                "War Crimes",
                "Warning",
                "Water",
                "WCNSF (Wounded Child No Surviving Family)",
                "Winter conditions",
                "Women",
                "Women's clothing (inc. lingerie)",

                # Countries & Organizations
                "AIPAC (American Israel Public Affairs Committee)",
                "ACRI (The association for Civil Rights in Israel)",
                "Al Jazeera",
                "Al-Azhar University",
                "Amnesty International",
                "Australia",
                "Bar-Ilan University",
                "Begin-Sadat Center for Strategic Studies",
                "COGAT (The Coordination of the Israeli Government Activities in the Territories)",
                "Columbia University",
                "Egypt",
                "Elbit",
                "EU (European Union)",
                "FAJR Scientific",
                "FAO (The Food and Agriculture Organization of the United Nations)",
                "Foundation for the Defense of Democracies",
                "Gaza Health Ministry",
                "Gaza Police",
                "Germany",
                "Gisha",
                "Hamas",
                "HaMoked Center for the Defense of the Individual",
                "Hezbollah",
                "Hind Rajab Foundation",
                "Hostages and Missing Families Forum",
                "Houthis (Ansar Allah)",
                "Human Rights Watch",
                "IDF (Israel Defense Forces)",
                "ICC (International Criminal Court)",
                "ICJ (International Court of Justice)",
                "ICRC (International Committee of the Red Cross)",
                "Iran",
                "IRC (International Rescue Committee)",
                "Islamic Jihad",
                "Israel Antiquities Authority",
                "Israeli Education Ministry",
                "Israeli Foreign Ministry",
                "Israeli Government",
                "Israeli Health Ministry",
                "Israeli Incarceration System",
                "Israeli Parliament (Knesset)",
                "Israeli Police",
                "Israeli Prison",
                "Israeli Supreme Court",
                "Jerusalem Institute for Strategy and Security",
                "Jordan",
                "JVP (Jewish Voice for Peace)",
                "Lebanon",
                "Likud",
                "MAP (Medical Aid for Palestinians)",
                "Meta Platforms",
                "Mossad",
                "MSF - Médecins Sans Frontières (Doctors Without Borders)",
                "Nachala (settler movement)",
                "Norwegian Refugee Council",
                "OCHA (UN Office for the Coordination of Humanitarian Affairs)",
                "Palestinian Authority",
                "PAMA (Palestinian American Medical Association)",
                "PCD (Palestinian Civil Defence)",
                "Physicians for Human Rights Israel",
                "Palestinian Ministry of Education",
                "PRCS (Palestinian Red Crescent Society)",
                "Project HOPE",
                "Qatar",
                "Saudi Arabia",
                "Shin Bet",
                "South Africa",
                "Syria",
                "Tsav 9",
                "UN (United Nations)",
                "UNESCO (United Nations Educational, Scientific and Cultural Organization)",
                "UNFPA (United Nations Population Fund)",
                "UNICEF (United Nations Children's Fund)",
                "United Kingdom",
                "United States",
                "UNRWA (The UN Relief and Works Agency for Palestine Refugees)",
                "UN Security Council",
                "USAID (United States Agency for International Development)",
                "US Department of State",
                "Vatican",
                "WHO (World Health Organization)",
                "World Central Kitchen",
                "World Food Programme",
                "Zazim",

                #Locations
                "Al Ahli Baptist Hospital"
                "Al-Amal Hospital",
                "Al-Aqsa Hospital",
                "Al Aqsa University",
                "Al-Awda Hospital",
                "Al Azhar University",
                "Al Buriej",
                "Al Mawasi",
                "Al Nazla",
                "Al-Rantisi Hospital",
                "Al Rashid Coastal Road",
                "Al-Shati Refugee Camp",
                "Al-Shifa Hospital",
                "Al Yarmouk Stadium Refugee Camp",
                "Al-Yemen Al-Saeed Hospital",
                "Ashdod Port",
                "Beer Sheva",
                "Beit Hanoun",
                "Beit Lahiya",
                "Central Gaza Strip",
                "Central Israel",
                "Cyprus",
                "Damon Prison",
                "Deir al Balah",
                "East Jerusalem",
                "Egypt",
                "Erez Crossing",
                "Europe",
                "Gaza City",
                "Gaza Strip",
                "Gilboa Prison",
                "Hebron",
                "Iran",
                "Iraq",
                "Israel",
                "Israeli Parliament (Knesset)",
                "Israeli Prison",
                "Jabaliya",
                "Jabaliya Camp",
                "Jabaliya City",
                "Jericho",
                "Jerusalem",
                "Jordan",
                "Jordan Valley",
                "Kamal Adwan Hospital",
                "Karni Crossing",
                "Kerem Shalom Crossing",
                "Khan Younis",
                "Khuza'a",
                "Ktzi'ot Prison",
                "Lebanon",
                "Megido Prison",
                "Mohammed Yousef El-Najar Hospital",
                "Morag Corridor",
                "Nablus",
                "Nasser Hospital",
                "Negev",
                "Netzarim Corridor",
                "Nitzana Border Crossing",
                "North Gaza",
                "Northern Israel",
                "Nur Shams Refugee Camp",
                "Nuseirat Refugee Camp",
                "Philadelphi Corridor",
                "Qalqilya",
                "Qatar",
                "Rafah",
                "Rafah Crossing",
                "Ramallah",
                "Red Cross Field Hospital",
                "Sde Teiman Detention Center",
                "Sheikh Radwan",
                "Shujjaiya",
                "South Gaza",
                "Southern Israel",
                "Tel Aviv",
                "The European Hospital",
                "The Indonesian Hospital",
                "Tul Karem",
                "Turkish-Palestinian Friendship Hospital",
                "USA",
                "West Bank",
                "Western Negev (Otef)",
                "Zaytun Neighborhood",
                "Zikim Crossing",

                # Figures
                "Aaron Bushnell",
                "Ahmad Tibi",
                "Almog Boker",
                "Almog Cohen",
                "Amihai Eliyahu",
                "Amit Segal",
                "António Guterres",
                "Antony Blinken",
                "Avichay Adraee",
                "Benjamin Netanyahu",
                "Benny Gantz",
                "Benny Morris",
                "Bezalel Smotritch",
                "Cochav Elkayam-Levy",
                "Daniel Hagari",
                "Daniella Weiss",
                "Danny Danon",
                "David Barnea",
                "Donald Trump",
                "Dr Adnan Al Bursh",
                "Dr Hussam Abu Safiya",
                "Dr Marwan Shafiq Alhamss",
                "Efraim Inbar",
                "Eitan Shamir",
                "Francesca Albanese",
                "Gali Baharav-Miara",
                "Giora Eiland",
                "Guy Basson",
                "Guy Hochman",
                "Hassan Nasrallah",
                "Herzi Halevi",
                "Hossam Shabat",
                "Isaac Herzog",
                "Ismail Haniyeh",
                "Israel Katz",
                "Itamar Ben-Gvir",
                "James Elder",
                "Jake Sullivan",
                "Jibril Ghatab El-Kahlout",
                "Joe Biden",
                "John Kirby",
                "Joseph Borrell",
                "Kamala Harris",
                "Karim Khan",
                "Kobi Yaakobi",
                "Lloyd Austin",
                "Mahmoud Abbas",
                "May Golan",
                "Merav Michaeli",
                "Martin Shaw",
                "Marwan Barghouti",
                "Mohammed bin Salman Al Saud",
                "Mosab Abu Toha",
                "Moshe (Bogie) Yaalon",
                "Moshe Feiglin",
                "Mustafa Jamal Kahlout",
                "Naftali Bennett",
                "Nisim Vatouri",
                "Nitzan Alon",
                "Nir Barkat",
                "Noam Tibon",
                "Ofer Cassif",
                "Omer Bar-Lev",
                "Philippe Lazzarini",
                "Pope Francis",
                "Ron Dermer",
                "Ronen Bar",
                "Sarah Netanyahu",
                "Shimon Boker",
                "Shimon Riklin",
                "Tali Gotliv",
                "Volker Türk",
                "Yaakov Bardugo",
                "Yahya Al-Sinwar",
                "Yair Golan",
                "Yair Lapid",
                "Yehuda Schlesinger",
                "Yehudah Vach",
                "Yehuda Vald",
                "Yinon Magal",
                "Yoav Gallant",
                "Zvi Sukkot",
                "Zvi Yehezkeli",
            ]   
            

def get_prompt(state: AgentState):
    url = state["url"]
    extracted_data = state["result"]
    url = state["url"]
    title = extracted_data["title"]
    content = extracted_data["article_body"]
    author = extracted_data["author"]
    datetime = extracted_data["datetime"]
    prompt_template = f"""Analyze this content and extract specific metadata.

    URL: {url}
    Title: {title}
    Author: {author}
    Date: {datetime}
    Content: {content}

    Instructions:
    1. For dates:
    - Publication date: When the content was published
    - Event date: When the described events occurred
    - Use YYYY-MM-DD format
    - For date ranges use: YYYY-MM-DD to YYYY-MM-DD
    - If only month/year available, use first day: YYYY-MM-01
    - If no date is available, return an empty string

    2. For content type, classify as:
    - Official Report: Research papers, formal investigations, detailed reports
    - Official Statement: Press releases, announcements, declarations
    - Opinion: Editorial content, opinion pieces, commentary
    - Testimony: First-hand accounts, witness statements
    - Journalistic Report: News articles, investigative journalism
    - Analysis: Analysis, commentary
    - Open letter: Letters to the editor, letters to the government, letters to the media
    - News: Breaking news, time-sensitive reporting
    - Post: Social media posts, short updates

    3. For media type, classify as:
    - Video: Video content, broadcasts
    - Photo: Photo galleries, image-focused content
    - Audio: Audio content, podcasts
    - Text: Text content, articles, reports

    4. For tags:
    - IMPORTANT: You must ONLY use tags from the following list. DO NOT create any new tags:
    {ALLOWED_TAGS}
    - Select ONLY the most relevant tags from this list that are reflected in the content
    - Format as an array of strings
    - If no tags from the list apply, return an empty array

    Return a JSON object with these exact fields:
    
    {{
        "summary": "One clear, informative sentence summarizing the main content",
        "date_published": "YYYY-MM-DD",
        "event_date": "YYYY-MM-DD or YYYY-MM-DD to YYYY-MM-DD",
        "type": "One of the content types listed above",
        "media": "One of the media types listed above",
        "language": "The primary language of the content",
        "platform": "The website or platform where content is published",
        "author": "The content author or organization",
        "tags": ["relevant", "topic", "tags"],
        "figures": "key inviduals. mentioned"
    }}
    - All string values (including "summary" and "tags") **must be in English**.
    
    Important
    - Even if the content is in non-english language (e.g: Hebrew, French etc...) your output should be in *English*.
    - Extract information only from the provided content
    - Leave field empty ("") if information is not explicitly present
    - For platform, extract from the URL or content source
    - For language, specify if clearly identifiable
    - Tags should ONLY be from the provided list, do not create new ones
    - Search for publication date in the content's metadata
    - If no publication date is found, use the creation date of the content
    - Always return content processed in English
    """
    return prompt_template

def summarizer(state: AgentState) -> AgentState:
    state["summarizer"] = get_llm()
    prompt = get_prompt(state)
    state["summary"] = state["summarizer"].invoke(prompt)
    return state